'use client';

import { useState, useCallback, useMemo } from 'react';
import Column from './Column';
import AuraAssistant from './AuraAssistant';

const INITIAL_TASKS = [
  { id: 't1', title: 'Architect Database', description: 'Design Firestore schema for real-time sync.', status: 'todo', effort: 'Medium', assignee: 'AI System' },
  { id: 't2', title: 'Implement Auth', description: 'Setup Firebase Authentication.', status: 'in-progress', effort: 'High', assignee: 'Security Team' }
];

const COLUMNS = [
  { id: 'todo', title: 'To Do' },
  { id: 'in-progress', title: 'In Progress' },
  { id: 'done', title: 'Done' }
];

/**
 * AuraBoard Component
 * The main collaborative workspace integrating a Kanban board with an AI Assistant.
 * Uses advanced memoization and state management for optimal rendering efficiency.
 * 
 * @returns {JSX.Element} The rendered AuraBoard component
 */
export default function AuraBoard() {
  const [tasks, setTasks] = useState(INITIAL_TASKS);

  /**
   * Handles dropping a task into a new column via mouse interaction.
   * @param {DragEvent} e - The HTML drag event
   * @param {string} status - The ID of the target column
   */
  const handleDrop = useCallback((e, status) => {
    e.preventDefault();
    const taskId = e.dataTransfer.getData('taskId');
    if (!taskId) return;
    
    setTasks(prevTasks => 
      prevTasks.map(t => t.id === taskId ? { ...t, status } : t)
    );
  }, []);

  /**
   * Handles moving a task to the next logical column via keyboard interaction (A11y).
   * @param {string} taskId - The unique ID of the task to move
   */
  const handleMove = useCallback((taskId) => {
    setTasks(prevTasks => {
      const taskIndex = prevTasks.findIndex(t => t.id === taskId);
      if (taskIndex === -1) return prevTasks;
      
      const task = prevTasks[taskIndex];
      const currentStatusIndex = COLUMNS.findIndex(c => c.id === task.status);
      
      // Move to next column if not already in the last one
      if (currentStatusIndex < COLUMNS.length - 1) {
        const newStatus = COLUMNS[currentStatusIndex + 1].id;
        const newTasks = [...prevTasks];
        newTasks[taskIndex] = { ...task, status: newStatus };
        return newTasks;
      }
      return prevTasks;
    });
  }, []);

  /**
   * Processes new tasks generated by the Gemini AI Coach.
   * Generates secure unique IDs and appends them to the To Do column.
   * @param {Array} newTasks - Array of task objects from the AI
   */
  const handleAddAITasks = useCallback((newTasks) => {
    if (!Array.isArray(newTasks)) return;

    const formattedTasks = newTasks.map(t => ({
      ...t,
      // Fallback ID generation ensuring uniqueness
      id: `ai-${Date.now()}-${Math.random().toString(36).substring(2, 9)}`,
      status: 'todo',
      assignee: 'AI Generated'
    }));
    
    setTasks(prev => [...prev, ...formattedTasks]);
  }, []);

  // Memoize column rendering to prevent unnecessary re-renders of the entire board
  const boardColumns = useMemo(() => {
    return COLUMNS.map(column => {
      // Filter tasks for this specific column
      const columnTasks = tasks.filter(t => t.status === column.id);
      return (
        <Column 
          key={column.id}
          column={column}
          tasks={columnTasks}
          onDrop={handleDrop}
          onMove={handleMove}
        />
      );
    });
  }, [tasks, handleDrop, handleMove]);

  return (
    <div className="workspace">
      <div 
        className="board-container" 
        role="region" 
        aria-label="Interactive Task Board"
      >
        {boardColumns}
      </div>
      
      <AuraAssistant onSuggestTasks={handleAddAITasks} />
    </div>
  );
}
