import { renderHook, act } from '@testing-library/react';
import { useKanban } from '../hooks/useKanban';
import { INITIAL_TASKS } from '../lib/constants';

describe('useKanban Custom Hook', () => {
  test('initializes with default tasks', () => {
    const { result } = renderHook(() => useKanban());
    expect(result.current.tasks).toEqual(INITIAL_TASKS);
    expect(result.current.isPending).toBe(false);
  });

  test('moveTask updates a tasks status', () => {
    const { result } = renderHook(() => useKanban());
    
    act(() => {
      // Move task t1 from 'todo' to 'in-progress'
      result.current.moveTask('t1', 'in-progress');
    });

    const updatedTask = result.current.tasks.find(t => t.id === 't1');
    expect(updatedTask.status).toBe('in-progress');
  });

  test('addTasks generates secure unique IDs and appends tasks', () => {
    const { result } = renderHook(() => useKanban());
    
    const newAITasks = [
      { title: 'New AI Task', description: 'Generated by Gemini', effort: 'Low' }
    ];

    act(() => {
      result.current.addTasks(newAITasks);
    });

    // Should have original 2 + 1 new task
    expect(result.current.tasks.length).toBe(3);
    const addedTask = result.current.tasks[2];
    expect(addedTask.title).toBe('New AI Task');
    expect(addedTask.id).toMatch(/^ai-\d+-/); // Validates secure ID format
    expect(addedTask.status).toBe('todo');
  });
});
